export DEFAULT_USER=rrap
export CUSTOMER=staging
export DOMAIN=staging.fabricpandit.com
export CUSTOMER_GIT_CLONING_URL=
export DEVELOPER_ENV_PHP=
export DEVELOPER_CONFIG_PHP=
export GIT_URL=
export GIT_BRANCH=
export PLATFORM=M2


export DOWNLOAD_USER=rrap
export DOWNLOAD_PASSWORD='Giryvq6m$'
#export API_KEY=respectorigin_api
#export API_PASSWD=mcgsSzn8
#export API_SERVER=api8.luroconnect.com
ISAWS=1

#export NODE_PUB_IP=13.235.77.189
#export DISK_DEVICE_NAME=/dev/nvme1n1
USE=""edge+app+db+varnish""
